# Run

# Health

### Get API Health Status
GET {{API_HostAddress}}/health
Accept: application/json

### Get API Health Status with Auth
GET {{API_HostAddress}}/health/auth
Accept: application/json
Authorization: Bearer {{access_token}}

### Login User
POST {{Keycloak_HostAddress}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = {{client_id}} &
client_secret = {{client_secret}} &
grant_type = {{grant_type}} &
username = admin &
password = P@ssword2025

> {%
    client.global.set("access_token", response.body.access_token);
    console.log("JWT Token:", client.global.get("access_token"));
%}

###

# Manager

### Create Password
POST {{API_HostAddress}}/manager/create
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "My first password",
  "password": "qwerty123456asdfgh"
}

### Get all password for logged in user
GET {{API_HostAddress}}/manager/getall
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  
}
