# Docker command
# docker compose -f sqlserver_docker.yml up -d

# Test connection from Powershell
# Test-NetConnection -ComputerName localhost -Port 1433

# Open firewall
# New-NetFirewallRule -DisplayName "WSL2 SQL Server" -Direction Inbound -Action Allow -Protocol TCP -LocalPort 1433



services:
  # SQL Server to use for API
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - backend-network

volumes:
  sql_data:

networks:
  backend-network:
    name: backend-network
